version: '3.3'
services:

  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_SLUG}_php
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network


# Docker Networks
networks:
  app_network:
    driver: bridge